enum Lvl0 {
  AcidSplash = 'AcidSplash',
  BladeWard = 'BladeWard',
  ChillTouch = 'ChillTouch',
  DancingLights = 'DancingLights',
  FireBolt = 'FireBolt',
  Friends = 'Friends',
  Light = 'Light',
  MageHand = 'MageHand',
  Mending = 'Mending',
  Message = 'Message',
  MinorIllusion = 'MinorIllusion',
  PoisonSpray = 'PoisonSpray',
  Prestidigitation = 'Prestidigitation',
  RayOfFrost = 'RayOfFrost',
  ShockingGrasp = 'ShockingGrasp',
  TrueStrike = 'TrueStrike',
}

enum Lvl1 {
  Alarm = 'Alarm',
  BurningHands = 'BurningHands',
  CharmPerson = 'CharmPerson',
  ChromaticOrb = 'ChromaticOrb',
  ColorSpray = 'ColorSpray',
  ComprehendLanguages = 'ComprehendLanguages',
  DetectMagic = 'DetectMagic',
  DisguiseSelf = 'DisguiseSelf',
  ExpeditiousRetreat = 'ExpeditiousRetreat',
  FalseLife = 'FalseLife',
  FeatherFall = 'FeatherFall',
  FindFamiliar = 'FindFamiliar',
  FogCloud = 'FogCloud',
  Grease = 'Grease',
  Identify = 'Identify',
  IllusoryScript = 'IllusoryScript',
  Jump = 'Jump',
  Longstrider = 'Longstrider',
  MageArmor = 'MageArmor',
  MagicMissile = 'MagicMissile',
  ProtectionFromEvilAndGood = 'ProtectionFromEvilAndGood',
  RayOfSickness = 'RayOfSickness',
  Shield = 'Shield',
  SilentImage = 'SilentImage',
  Sleep = 'Sleep',
  TashaHideousLaughter = 'TashaHideousLaughter',
  TensersFloatingDisk = 'TensersFloatingDisk',
  Thunderwave = 'Thunderwave',
  UnseenServant = 'UnseenServant',
  WitchBolt = 'WitchBolt',
}

enum Lvl2 {
  AlterSelf = 'AlterSelf',
  ArcaneLock = 'ArcaneLock',
  BlindnessDeafness = 'BlindnessDeafness',
  Blur = 'Blur',
  CloudOfDaggers = 'CloudOfDaggers',
  ContinualFlame = 'ContinualFlame',
  CrownOfMadness = 'CrownOfMadness',
  Darkness = 'Darkness',
  Darkvision = 'Darkvision',
  DetectThoughts = 'DetectThoughts',
  EnlargeReduce = 'EnlargeReduce',
  FlamingSphere = 'FlamingSphere',
  GentleRepose = 'GentleRepose',
  GustOfWind = 'GustOfWind',
  HoldPerson = 'HoldPerson',
  Invisibility = 'Invisibility',
  Knock = 'Knock',
  Levitate = 'Levitate',
  LocateObject = 'LocateObject',
  MagicMouth = 'MagicMouth',
  MagicWeapon = 'MagicWeapon',
  MelFAcidsArrow = 'MelFAcidsArrow',
  MirrorImage = 'MirrorImage',
  MistyStep = 'MistyStep',
  NystulsMagicAura = 'NystulsMagicAura',
  PhantasmalForce = 'PhantasmalForce',
  RayOfEnfeeblement = 'RayOfEnfeeblement',
  RopeTrick = 'RopeTrick',
  ScorchingRay = 'ScorchingRay',
  SeeInvisibility = 'SeeInvisibility',
  Shatter = 'Shatter',
  SpiderClimb = 'SpiderClimb',
  Suggestion = 'Suggestion',
  Web = 'Web',
}

enum Lvl3 {
  AnimateDead = 'AnimateDead',
  BestowCurse = 'BestowCurse',
  Blink = 'Blink',
  Clairvoyance = 'Clairvoyance',
  Counterspell = 'Counterspell',
  DispelMagic = 'DispelMagic',
  Fear = 'Fear',
  FeignDeath = 'FeignDeath',
  Fireball = 'Fireball',
  Fly = 'Fly',
  GaseousForm = 'GaseousForm',
  GlyphOfWarding = 'GlyphOfWarding',
  Haste = 'Haste',
  HypnoticPattern = 'HypnoticPattern',
  LeomundsTinyHut = 'LeomundsTinyHut',
  LightningBolt = 'LightningBolt',
  MagicCircle = 'MagicCircle',
  MajorImage = 'MajorImage',
  Nondetection = 'Nondetection',
  PhantomSteed = 'PhantomSteed',
  ProtectionFromEnergy = 'ProtectionFromEnergy',
  Sending = 'Sending',
  SleetStorm = 'SleetStorm',
  Slow = 'Slow',
  StinkingCloud = 'StinkingCloud',
  Tongues = 'Tongues',
  VampiricTouch = 'VampiricTouch',
  WaterBreathing = 'WaterBreathing',
}

enum Lvl4 {
  ArcaneEye = 'ArcaneEye',
  Banishment = 'Banishment',
  Blight = 'Blight',
  Confusion = 'Confusion',
  ConjureMinorElementals = 'ConjureMinorElementals',
  ControlWater = 'ControlWater',
  DimensionDoor = 'DimensionDoor',
  EvardsBlackTentacles = 'EvardsBlackTentacles',
  Fabricate = 'Fabricate',
  FireShield = 'FireShield',
  GreaterInvisibility = 'GreaterInvisibility',
  HallucinatoryTerrain = 'HallucinatoryTerrain',
  IceStorm = 'IceStorm',
  LeomundsSecretChest = 'LeomundsSecretChest',
  LocateCreature = 'LocateCreature',
  MordenkainensFaithfulHound = 'MordenkainensFaithfulHound',
  MordenkainensPrivateSanctum = 'MordenkainensPrivateSanctum',
  OtilukesResilientSphere = 'OtilukesResilientSphere',
  PhantasmalKiller = 'PhantasmalKiller',
  Polymorph = 'Polymorph',
  StoneShape = 'StoneShape',
  Stoneskin = 'Stoneskin',
  WallOfFire = 'WallOfFire',
}

enum Lvl5 {
  AnimateObjects = 'AnimateObjects',
  BigbysHand = 'BigbysHand',
  Cloudkill = 'Cloudkill',
  ConeOfCold = 'ConeOfCold',
  ConjureElemental = 'ConjureElemental',
  ContactOtherPlane = 'ContactOtherPlane',
  Creation = 'Creation',
  DominatePerson = 'DominatePerson',
  Dream = 'Dream',
  Geas = 'Geas',
  HoldMonster = 'HoldMonster',
  LegendLore = 'LegendLore',
  Mislead = 'Mislead',
  ModifyMemory = 'ModifyMemory',
  Passwall = 'Passwall',
  PlanarBinding = 'PlanarBinding',
  RarysTelepathicBond = 'RarysTelepathicBond',
  Scrying = 'Scrying',
  Seeming = 'Seeming',
  Telekinesis = 'Telekinesis',
  TeleportationCircle = 'TeleportationCircle',
  WallOfForce = 'WallOfForce',
  WallOfStone = 'WallOfStone',
}
enum Lvl6 {
  ArcaneGate = 'ArcaneGate',
  ChainLightning = 'ChainLightning',
  CircleOfDeath = 'CircleOfDeath',
  Contingency = 'Contingency',
  CreateUndead = 'CreateUndead',
  Disintegrate = 'Disintegrate',
  DrawmijsInstantSummons = 'DrawmijsInstantSummons',
  Eyebite = 'Eyebite',
  FleshToStone = 'FleshToStone',
  GlobeOfInvulnerability = 'GlobeOfInvulnerability',
  GuardsAndWards = 'GuardsAndWards',
  MagicJar = 'MagicJar',
  MassSuggestion = 'MassSuggestion',
  MoveEarth = 'MoveEarth',
  OtilukeFreezingSphere = 'OtilukeFreezingSphere',
  OttoIrresistibleDance = 'OttoIrresistibleDance',
  ProgrammedIllusion = 'ProgrammedIllusion',
  Sunbeam = 'Sunbeam',
  TrueSeeing = 'TrueSeeing',
  WallOfIce = 'WallOfIce',
}

enum Lvl7 {
  DelayedBlastFireball = 'DelayedBlastFireball',
  Etherealness = 'Etherealness',
  FingerOfDeath = 'FingerOfDeath',
  Forcecage = 'Forcecage',
  MirageArcane = 'MirageArcane',
  MordenkainensMagnificentMansion = 'MordenkainensMagnificentMansion',
  MordenkainensSword = 'MordenkainensSword',
  PlaneShift = 'PlaneShift',
  PrismaticSpray = 'PrismaticSpray',
  ProjectImage = 'ProjectImage',
  ReverseGravity = 'ReverseGravity',
  Sequester = 'Sequester',
  Simulacrum = 'Simulacrum',
  Symbol = 'Symbol',
  Teleport = 'Teleport',
}

enum Lvl8 {
  AntimagicField = 'AntimagicField',
  AntipathySympathy = 'AntipathySympathy',
  Clone = 'Clone',
  ControlWeather = 'ControlWeather',
  Demiplane = 'Demiplane',
  DominateMonster = 'DominateMonster',
  Feeblemind = 'Feeblemind',
  IncendiaryCloud = 'IncendiaryCloud',
  Maze = 'Maze',
  MindBlank = 'MindBlank',
  PowerWordStun = 'PowerWordStun',
  Sunburst = 'Sunburst',
  Telepathy = 'Telepathy',
  TrapTheSoul = 'TrapTheSoul',
}
enum Lvl9 {
  AstralProjection = 'AstralProjection',
  Foresight = 'Foresight',
  Gate = 'Gate',
  Imprisonment = 'Imprisonment',
  MeteorSwarm = 'MeteorSwarm',
  PowerWordKill = 'PowerWordKill',
  PrismaticWall = 'PrismaticWall',
  Shapechange = 'Shapechange',
  TimeStop = 'TimeStop',
  TruePolymorph = 'TruePolymorph',
  Weird = 'Weird',
  Wish = 'Wish',
}

const WizardSpells = {
  ...Lvl0,
  ...Lvl1,
  ...Lvl2,
  ...Lvl3,
  ...Lvl4,
  ...Lvl5,
  ...Lvl6,
  ...Lvl7,
  ...Lvl8,
  ...Lvl9,
};

// eslint-disable-next-line @typescript-eslint/no-redeclare
export type WizardSpells = typeof WizardSpells;

export { WizardSpells, Lvl0, Lvl1, Lvl2, Lvl3, Lvl4, Lvl5, Lvl6, Lvl7, Lvl8, Lvl9 };
export default {
  AllSpells: WizardSpells,
  Lvl0,
  Lvl1,
  Lvl2,
  Lvl3,
  Lvl4,
  Lvl5,
  Lvl6,
  Lvl7,
  Lvl8,
  Lvl9,
};
